services:
  app:
    build: .
    container_name: personal-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    environment:
      - NODE_ENV=development
    # Use tty to keep container running for development
    tty: true
    stdin_open: true
    # Override the default command for now
    command: >
      sh -c "
      echo 'Ubuntu-based development environment ready' &&
      echo 'Node.js version:' && node --version &&
      echo 'npm version:' && npm --version &&
      echo 'Installing dependencies...' &&
      npm install &&
      echo 'Starting development server...' &&
      npm run dev
      "